2024-06-28 11:30:05,483 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 11:35:36,240 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 11:36:24,181 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 11:51:27,970 utils.py[line:227] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-06-28 11:51:27,971 main.py[line:82] - ERROR - 处理失败
2024-06-28 11:51:27,977 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 11:55:18,328 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 11:59:41,747 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 12:03:47,921 utils.py[line:227] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-06-28 12:03:47,922 main.py[line:82] - ERROR - 处理失败
2024-06-28 12:03:47,922 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 12:06:28,421 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 12:12:04,287 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 12:14:07,667 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 12:15:23,671 utils.py[line:101] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 12:17:16,305 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 12:18:43,577 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 12:20:46,118 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 12:22:39,747 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 12:26:07,385 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 14:52:26,065 utils.py[line:101] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 14:55:54,058 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 14:56:51,979 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 15:18:10,133 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 15:20:59,777 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 15:23:38,138 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 15:31:44,479 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 15:48:30,938 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 16:03:04,564 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 16:07:31,464 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 16:25:01,278 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 16:29:57,905 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 16:49:10,627 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 16:50:30,739 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 16:52:40,850 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 17:01:43,963 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 17:05:56,524 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 17:09:33,282 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 17:12:01,788 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 17:13:27,639 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-28 17:20:43,034 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-29 15:43:42,727 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-29 15:52:02,852 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-29 16:08:30,885 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-29 16:21:17,909 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-29 16:31:42,830 utils.py[line:227] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-06-29 16:31:42,831 main.py[line:92] - ERROR - 处理失败
2024-06-29 16:31:42,831 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-29 16:35:42,748 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-29 16:44:57,631 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-29 16:49:04,069 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-29 16:53:18,366 utils.py[line:158] - ERROR - 图像指令转换失败，数据长度错误
2024-06-29 17:17:24,471 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-29 17:44:57,312 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-29 17:48:31,343 utils.py[line:230] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-06-29 17:48:31,344 main.py[line:95] - ERROR - 处理失败
2024-06-29 17:48:31,344 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-29 17:52:27,224 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-29 18:40:34,394 utils.py[line:230] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-06-29 18:40:34,395 main.py[line:95] - ERROR - 处理失败
2024-06-29 18:40:34,395 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-30 12:45:15,007 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-30 12:57:37,170 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-30 13:01:35,413 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-30 14:14:42,010 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-30 14:24:06,845 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-06-30 14:35:07,953 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-01 15:27:37,749 utils.py[line:161] - ERROR - 图像指令转换失败，数据长度错误
2024-07-01 16:23:59,608 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-01 16:27:39,666 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-01 16:45:20,986 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-01 16:49:36,061 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-01 16:57:25,351 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-01 17:01:32,692 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-01 17:22:45,049 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-01 17:25:23,065 utils.py[line:230] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-01 17:25:23,065 main.py[line:101] - ERROR - 处理失败
2024-07-01 17:25:23,065 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-01 17:27:39,278 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-01 17:29:37,321 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-01 17:31:32,282 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-01 17:33:22,204 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-01 17:35:32,399 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-01 17:46:20,681 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-01 17:47:51,507 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-01 17:51:45,559 utils.py[line:230] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-01 17:51:45,559 main.py[line:101] - ERROR - 处理失败
2024-07-01 17:51:45,560 utils.py[line:84] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-04 14:08:48,265 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-04 14:08:48,265 main.py[line:108] - ERROR - 处理失败
2024-07-04 14:08:49,453 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-04 14:08:49,453 main.py[line:108] - ERROR - 处理失败
2024-07-04 14:08:50,744 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-04 14:08:50,744 main.py[line:108] - ERROR - 处理失败
2024-07-04 14:08:50,744 pipe_utils.py[line:85] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-04 14:27:19,068 pipe_utils.py[line:85] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-04 16:41:47,465 pipe_utils.py[line:85] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-04 16:45:24,931 pipe_utils.py[line:85] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-04 16:49:02,620 pipe_utils.py[line:85] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-04 16:51:48,679 pipe_utils.py[line:85] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-04 16:53:58,252 pipe_utils.py[line:85] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-04 17:00:49,493 pipe_utils.py[line:85] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-04 17:08:10,792 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-04 17:08:10,793 main.py[line:110] - ERROR - 处理失败
2024-07-04 17:08:12,041 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-04 17:08:12,042 main.py[line:110] - ERROR - 处理失败
2024-07-04 17:08:13,179 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-04 17:08:13,179 main.py[line:110] - ERROR - 处理失败
2024-07-04 17:08:14,424 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-04 17:08:14,425 main.py[line:110] - ERROR - 处理失败
2024-07-04 17:08:15,606 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-04 17:08:15,606 main.py[line:110] - ERROR - 处理失败
2024-07-04 17:08:16,934 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-04 17:08:16,934 main.py[line:110] - ERROR - 处理失败
2024-07-04 17:08:18,134 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-04 17:08:18,134 main.py[line:110] - ERROR - 处理失败
2024-07-04 17:08:19,383 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-04 17:08:19,383 main.py[line:110] - ERROR - 处理失败
2024-07-04 17:08:20,639 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-04 17:08:20,639 main.py[line:110] - ERROR - 处理失败
2024-07-04 17:08:21,809 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-04 17:08:21,809 main.py[line:110] - ERROR - 处理失败
2024-07-04 17:08:21,810 pipe_utils.py[line:85] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-04 17:18:14,994 pipe_utils.py[line:85] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-04 17:20:39,388 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-04 17:20:39,388 main.py[line:110] - ERROR - 处理失败
2024-07-04 17:20:40,562 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-04 17:20:40,563 main.py[line:110] - ERROR - 处理失败
2024-07-04 17:20:41,738 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-04 17:20:41,738 main.py[line:110] - ERROR - 处理失败
2024-07-04 17:20:43,017 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-04 17:20:43,017 main.py[line:110] - ERROR - 处理失败
2024-07-04 17:20:44,275 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-04 17:20:44,275 main.py[line:110] - ERROR - 处理失败
2024-07-04 17:20:45,548 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-04 17:20:45,548 main.py[line:110] - ERROR - 处理失败
2024-07-04 17:20:46,743 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-04 17:20:46,743 main.py[line:110] - ERROR - 处理失败
2024-07-04 17:20:47,987 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-04 17:20:47,987 main.py[line:110] - ERROR - 处理失败
2024-07-04 17:20:49,183 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-04 17:20:49,183 main.py[line:110] - ERROR - 处理失败
2024-07-04 17:20:50,393 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-04 17:20:50,394 main.py[line:110] - ERROR - 处理失败
2024-07-04 17:20:51,724 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-04 17:20:51,724 main.py[line:110] - ERROR - 处理失败
2024-07-04 17:20:52,901 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-04 17:20:52,901 main.py[line:110] - ERROR - 处理失败
2024-07-04 17:20:54,161 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-04 17:20:54,161 main.py[line:110] - ERROR - 处理失败
2024-07-04 17:20:55,332 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-04 17:20:55,333 main.py[line:110] - ERROR - 处理失败
2024-07-04 17:20:56,561 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-04 17:20:56,561 main.py[line:110] - ERROR - 处理失败
2024-07-04 17:20:56,561 pipe_utils.py[line:85] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-05 14:23:17,274 pipe_utils.py[line:85] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-05 14:52:48,462 pipe_utils.py[line:85] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-05 14:59:25,432 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-05 14:59:25,433 main.py[line:110] - ERROR - 处理失败
2024-07-05 14:59:25,433 pipe_utils.py[line:85] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-05 15:21:42,677 pipe_utils.py[line:85] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-07 16:11:16,751 pipe_utils.py[line:231] - ERROR - 发送指令失败，错误类型：(232, 'WriteFile', '管道正在被关闭。')
2024-07-07 16:11:16,752 main.py[line:125] - ERROR - 处理失败
2024-07-07 16:11:16,752 pipe_utils.py[line:85] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-07 16:25:38,533 pipe_utils.py[line:85] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
2024-07-07 16:34:38,764 pipe_utils.py[line:85] - ERROR - 数据接收失败，错误原因: (109, 'ReadFile', '管道已结束。')
